[workspace]
members = ["crates/boorust"]

[workspace.package]
version = "1.0.0"
edition = "2021"
rust-version = "1.73.0"

[workspace.dependencies]
pyo3 = { version = "0.20.0", extension-module = ["pyo3/extension-module"], features = ["extension-module"] }

