name: Create Version Tag
on:
  push:
    branches:
      - stable
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Git user
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'youremail@example.com'
      - name: Read Version File
        run: python get_version.py
      - name: Create Version Tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git tag $VERSION -m "New release"
          git push origin $VERSION
