# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    branches:
      - pre-release
      - pre-release-*
      - stable
      - stable-*
      - dev
      - dev-*

jobs:
  check_version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Version
        id: check_version
        run: python ./tools/set_version.py

      - name: Check out Version
        run: |
          echo "| Version: ${{ steps.check_version.outputs.VERSION }} in action"
          echo "| Tag exists: ${{ steps.check_version.outputs.exists }}"

  test_skip:
    if: ${{ startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: When Test is Skipped
    runs-on: ubuntu-latest
    steps:
      - name: Skip Test
        run: echo "Skip Test"

  test_py:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test on Python
    runs-on: ubuntu-latest
    needs:
      - check_version
    strategy:
      matrix:
        include:
          - step: python-latest
            depends_on: []
            python-version: "3.13"
          - step: python-oldest
            depends_on: [python-latest]
            python-version: "3.9"
          - step: python-other-310
            depends_on: [python-oldest]
            python-version: "3.10"
          - step: py-other-311
            depends_on: [py-other-310]
            python-version: "3.11"
          - step: py-other-312
            depends_on: [py-other-311]
            python-version: "3.12"
      fail-fast: false
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test Unit
        uses: ./.github/actions/test-unit
