# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    branches:
      - pre-release
      - pre-release-*
      - main
      - main-*
      - dev

jobs:
  test_py_latest:
    name: Test on Python Latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Run General Test
        uses: ./test-unit.yml
        with:
          ci_token: ${{ secrets.CI_TOKEN }}
          python_version: ${{ matrix.python-version }}

  test_py_oldest:
    name: Test on Python Other Versions
    needs: test_py_latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Run General Test
        uses: ./test-unit.yml
        with:
          ci_token: ${{ secrets.CI_TOKEN }}
          python_version: ${{ matrix.python-version }}

  test_other:
    name: Test on Python Other Versions
    needs:
      - test_py_latest
      - test_py_oldest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Run General Test
        uses: ./test-unit.yml
        with:
          ci_token: ${{ secrets.CI_TOKEN }}
          python_version: ${{ matrix.python-version }}
