name: General Test Unit

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to set up"
        required: true
        type: string
jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv wheel pip
          python -m pip install flake8 pytest matplotlib pep440
          pip install --upgrade urllib3
          # A bug waiting for fixing, https://github.com/pypa/setuptools/issues/3278
          pip install --upgrade --user setuptools setuptools_rust
          python -c "print('### Preparing setup.py '.ljust(70, '.'))"
          pip install -e .
          # python -c "print('### Preparing requirements.txt '.ljust(70, '.'))
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -c "print('### Dependencies are ready to go '.ljust(70, '.'))"
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
