---
name: Wheel Builds Stable
on:
  push:
    tags:
      - 0.[0-9]+.[0-9]+

jobs:
  build_wheels:
    if: github.repository == 'harui2019/qurry'
    name: Build wheels on ${{ matrix.vers }} by ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - vers: linux-x86_64
            os: ubuntu-latest
            archs: X64
          # - vers: linux-aarch64
          #   os: ubuntu-latest
          #   archs: ARM64 # Corss-compiling in test
          - vers: macOS-x86_64
            os: macos-13
            archs: X64
          # - vers: macOS-arm64
          #   os: macos-14
          #   archs: ARM64
          # - vers: windows-x86_64
          #   os: windows-latest
          #   archs: X64
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/qurrium

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: ${{ matrix.os == 'macos-14' && 'arm64' || 'x64' }}
      - name: MacOS Path Fix
        if: runner.os == 'macOS'
        run: export PATH="$pythonLocation:$PATH"

      - name: Reversion Stable
        run: |
          python -m pip install toml pep440
          python ./tools/set_version.py --release stable
          python ./tools/set_pyproject_qurry.py --release stable

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Set up
      - name: Set up QEMU
        if: matrix.vers == 'linux-aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Prepare CIBW
        run: |
          python -m pip install cibuildwheel==2.21.3 --upgrade
          echo "| $(python -m pip --version)"
          echo "| $(python -m pip list | grep cibuildwheel)"
      # Hint:
      # > Since we have some self-hosted runners,
      # > some of them may not work with the github actions workflow of cibuildwheel.
      # > Due to actions/setup-python@v5 cannot configure
      # > the environment of self-hosted runners properly in most of the cases.
      # > It made pypa/cibuildwheel@v2.21.3 can not install itself.
      # > So, we only use command line to build.

      # Build wheels
      - name: Build wheels
        if: matrix.vers != 'linux-aarch64'
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Build wheels (Linux aarch64)
        if: matrix.vers == 'linux-aarch64'
        run: |
          python -m cibuildwheel --output-dir wheelhouse --platform linux --arch aarch64

      # Upload the wheelhouse as an artifact
      - name: Wheelhouse Upload
        if: matrix.vers != 'linux-x86_64'
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          name: shared-wheel-builds

      - name: Early Publish distribution 📦 to PyPI for Linux X86_64
        if: matrix.vers == 'linux-x86_64'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse

  publish-to-testpypi:
    if: github.repository == 'harui2019/qurry'
    name: Publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    needs:
      - build_wheels
    strategy:
      fail-fast: false
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/qurrium

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: shared-wheel-builds
          path: deploy
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: deploy
